% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Lição 2 e 3},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Lição 2 e 3}
\author{}
\date{\vspace{-2.5em}2026-03-24}

\begin{document}
\maketitle

\textbf{EXERCÍCIO 2}

Carregando pacotes

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.2.0     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.1
## v lubridate 1.9.4     v tibble    3.2.1
## v purrr     1.0.4     v tidyr     1.3.1
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(kableExtra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Anexando pacote: 'kableExtra'
## 
## O seguinte objeto é mascarado por 'package:dplyr':
## 
##     group_rows
\end{verbatim}

Importação de dados

\textbf{Ex 1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{municipios }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"C:/Users/Gustavo/Downloads/municipios\_virgula.csv"}\NormalTok{)}
\FunctionTok{View}\NormalTok{(municipios)}
\FunctionTok{str}\NormalTok{(municipios)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    15 obs. of  5 variables:
##  $ nome_municipio: chr  "São Paulo" "Rio de Janeiro" "Belo Horizonte" "Salvador" ...
##  $ uf            : chr  "SP" "RJ" "MG" "BA" ...
##  $ populacao     : int  11451999 6211423 2315560 2418005 1773733 2428678 2063547 1555039 1332570 1303389 ...
##  $ idh           : num  0.805 0.799 0.81 0.759 0.823 0.754 0.737 0.772 0.805 0.746 ...
##  $ pib_per_capita: num  54258 49528 33049 20233 42935 ...
\end{verbatim}

R: temos 15 municípios divididos em 5 colunas: nome\_municipio, uf,
populacao, idh e pib\_per\_capita

\textbf{Ex 2}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# \textless{}{-} read.csv("C:/Users/Gustavo/Downloads/municipios\_pontovirgula.csv")}

\NormalTok{municipos2 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv2}\NormalTok{(}\StringTok{"C:/Users/Gustavo/Downloads/municipios\_pontovirgula.csv"}\NormalTok{,}
                        \AttributeTok{fileEncoding =} \StringTok{"latin1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

R: primeiro aparece erro de leitura do código porque não é a formatação
padrão de leitura dos arquivos csv. Comumente é observado em csvs a
repartição de itens por vírgulas, não ponto e vírgula e as variaveis não
inteiras tem os algarismos decimais partidos por ponto final, não
vírgula como na língua brasileira.

\textbf{Ex 3}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eleicoes22 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"C:/Users/Gustavo/Downloads/eleicoes\_2022.csv"}\NormalTok{)}
\FunctionTok{filter}\NormalTok{(eleicoes22, municipio }\SpecialCharTok{==} \StringTok{"Pau D\textquotesingle{}Arco"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    municipio uf candidato partido votos percentual
## 1 Pau D'Arco PA      Lula      PT  2345      55.37
## 2 Pau D'Arco PA Bolsonaro      PL  1890      44.63
\end{verbatim}

R: A importação deu certo

\textbf{Ex 4}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{IDH\_municipios }\OtherTok{\textless{}{-}} \FunctionTok{read.csv2}\NormalTok{(}\StringTok{"C:/Users/Gustavo/Downloads/idh\_municipios.csv"}\NormalTok{,}
                            \AttributeTok{fileEncoding =} \StringTok{"latin1"}\NormalTok{)}
\FunctionTok{str}\NormalTok{(IDH\_municipios)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    25 obs. of  9 variables:
##  $ cod_ibge       : int  3550308 3304557 3106200 2927408 4106902 2304400 1302603 2611606 4314902 1501402 ...
##  $ municipio      : chr  "São Paulo" "Rio de Janeiro" "Belo Horizonte" "Salvador" ...
##  $ uf             : chr  "SP" "RJ" "MG" "BA" ...
##  $ regiao         : chr  "Sudeste" "Sudeste" "Sudeste" "Nordeste" ...
##  $ idh_2010       : num  0.805 0.799 0.81 0.759 0.823 0.754 0.737 0.772 0.805 0.746 ...
##  $ idh_educacao   : num  0.725 0.719 0.737 0.661 0.768 0.672 0.658 0.698 0.727 0.673 ...
##  $ idh_longevidade: num  0.855 0.845 0.856 0.835 0.855 0.824 0.812 0.825 0.857 0.818 ...
##  $ idh_renda      : num  0.843 0.84 0.841 0.79 0.85 0.773 0.75 0.798 0.835 0.756 ...
##  $ populacao_2010 : int  11253503 6320446 2375151 2675656 1751907 2452185 1802014 1537704 1409351 1393399 ...
\end{verbatim}

R: Sim, são numéricas

\textbf{Ex 6}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{municipios }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ idh, }\AttributeTok{y =} \FunctionTok{reorder}\NormalTok{(nome\_municipio, idh))) }\SpecialCharTok{+} \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"IDH"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{ylab}\NormalTok{(}\StringTok{"Município"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_light}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{text=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{20}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"IDH dos municípios em ordem}\SpecialCharTok{\textbackslash{}n}\StringTok{do maior para o menor"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Teste-lição_files/figure-latex/unnamed-chunk-6-1.pdf}}

R: Florianópolis apresenta maior IDH e Pau D'Arco menor IDH

\textbf{Ex 7}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ municipios }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\StringTok{\textquotesingle{}populacao total\textquotesingle{}} \OtherTok{=} \FunctionTok{sum}\NormalTok{(populacao),}
            \StringTok{\textquotesingle{}populacao media\textquotesingle{}} \OtherTok{=} \FunctionTok{mean}\NormalTok{(populacao))}
\FunctionTok{kable}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rr@{}}
\toprule\noalign{}
populacao total & populacao media \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
36601670 & 2440111 \\
\end{longtable}

R: Temos soma igual a 36601670 e média 2440111

\textbf{Ex 8}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ eleicoes22 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(candidato) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{soma\_candidatos =} \FunctionTok{sum}\NormalTok{(votos)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(soma\_candidatos))}
\FunctionTok{kable}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\toprule\noalign{}
candidato & soma\_candidatos \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Lula & 8249244 \\
Bolsonaro & 6861801 \\
Simone Tebet & 758133 \\
Ciro Gomes & 355023 \\
\end{longtable}

R: Essa é a votação final, indicando ``Lula'' como vencedor

\textbf{Ex 9}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ IDH\_municipios }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(regiao) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{soma\_idh =} \FunctionTok{mean}\NormalTok{(idh\_2010)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(soma\_idh))}
\FunctionTok{kable}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\toprule\noalign{}
regiao & soma\_idh \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Sul & 0.8250000 \\
Centro-Oeste & 0.7980000 \\
Sudeste & 0.7955000 \\
Nordeste & 0.7581429 \\
Norte & 0.7518000 \\
\end{longtable}

R: Sul tem maior IDH médio e Norte menor IDH médio

\textbf{Ex 10}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ eleicoes22 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(municipio) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_max}\NormalTok{(}\AttributeTok{order\_by =}\NormalTok{ votos) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ungroup}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{vencedor =}\NormalTok{ candidato)}
\FunctionTok{kable}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2857}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0429}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1429}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1571}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1429}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
municipio
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
uf
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
candidato
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
partido
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
votos
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
percentual
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
vencedor
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Belo Horizonte & MG & Lula & PT & 876543 & 52.55 & Lula \\
Florianópolis & SC & Bolsonaro & PL & 178901 & 57.08 & Bolsonaro \\
Pau D'Arco & PA & Lula & PT & 2345 & 55.37 & Lula \\
Rio de Janeiro & RJ & Lula & PT & 2345678 & 49.63 & Lula \\
Salvador & BA & Lula & PT & 1123456 & 63.97 & Lula \\
São José dos Campos & SP & Bolsonaro & PL & 245678 & 55.28 &
Bolsonaro \\
São Paulo & SP & Lula & PT & 3567890 & 48.82 & Lula \\
\end{longtable}

R: Exceto por Florianópolis e São Jóse dos Campos, que indicam
``Bolsonaro'' como vencedor, os demais municípios apresentam vitória de
``Lula''

\textbf{Ex 13}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{municipios }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(nome\_municipio, populacao), }\AttributeTok{y =}\NormalTok{ populacao)) }\SpecialCharTok{+} \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Município"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{ylab}\NormalTok{(}\StringTok{"População"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_light}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{20}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"População dos municípios em ordem}\SpecialCharTok{\textbackslash{}n}\StringTok{do menor para o maior"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\FunctionTok{label\_number}\NormalTok{(}\AttributeTok{accuracy =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Teste-lição_files/figure-latex/unnamed-chunk-11-1.pdf}}

R: São Paulo apresenta população muito numericamente superior que o Rio
de Janeiro, que também é 2 vezes maior numericamente que Fortaleza,
terceiro na ordem, mantendo uma decrescente gradual menos exorbitante
que os primeiros dois mencionados

\textbf{Ex 14}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{IDH\_municipios }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ idh\_educacao, }\AttributeTok{y =}\NormalTok{ idh\_renda, }\AttributeTok{color =}\NormalTok{ regiao)) }\SpecialCharTok{+} \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"IDH na Educação"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{ylab}\NormalTok{(}\StringTok{"IDH na Renda"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_light}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{text=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{20}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"IDH na educação e na renda por municípios"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Teste-lição_files/figure-latex/unnamed-chunk-12-1.pdf}}

R: Sul, Suldeste e Centro-Oeste apresentam IDH de renda e de educação
maiores do que as regiões Norte e Nordeste

\textbf{EXERCÍCIO 3}

\textbf{Ex 1:5}

Link para github referente aos exercícios sobre github:
\url{https://github.com/guhstar/exercicio-stat-basica}

\textbf{Ex 5 e 6 (? Markdown)}

\textbf{Texto Negrito} e \emph{Texto itálico}

Lista numerada:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Item 1
\item
  Item 2
\item
  Item 3
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{valores }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{30}\NormalTok{, }\DecValTok{40}\NormalTok{, }\DecValTok{50}\NormalTok{)}
\NormalTok{media }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(valores)}
\NormalTok{media}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30
\end{verbatim}

R: Média calculada com sucesso, lista feita e textos realizados

\textbf{Ex 7}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0049}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0138}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0118}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0098}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0089}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0089}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0138}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0217}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0108}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0118}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0177}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0128}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0177}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0236}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0217}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0207}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0285}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0266}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0256}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0266}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0246}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0246}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0276}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0600}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0217}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0285}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0197}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0650}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0354}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0148}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0098}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0197}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0167}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0138}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0226}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0157}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0108}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0108}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0108}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0148}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0679}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0679}}
  >{\raggedright\arraybackslash}p{(\linewidth - 84\tabcolsep) * \real{0.0591}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
ano
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_regiao
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_regiao
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_uf
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
sigla\_uf
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_uf
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
cod\_municipio
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_munic
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_metro
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_meso
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_meso
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_micro
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_micro
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_reg\_geo\_imediata
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_reg\_geo\_imediata
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
mun\_reg\_geo\_imediata
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_reg\_geo\_intermediaria
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_reg\_geo\_intermediaria
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
mun\_reg\_geo\_intermediaria
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_concentracao\_urbana
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_concentracao\_urbana
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
tipo\_concentracao\_urbana
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_arranjo\_populacional
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_arranjo\_populacional
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hierarquia\_urbana
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hierarquia\_urbana\_principais
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
codigo\_regiao\_rural
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
nome\_regiao\_rural
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
regiao\_rural\_classificacao
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
amazonia\_legal
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
semiarido
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
cidade\_de\_sao\_paulo
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vab\_agropecuaria
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vab\_industria
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vab\_servicos\_exclusivo
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vab\_adm\_publica
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vab\_total
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
impostos
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pib\_total
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pib\_per\_capita
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
atividade\_vab1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
atividade\_vab2
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
atividade\_vab3
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2013 & 1 & Norte & 11 & RO & Rondônia & 1100015 & Alta Floresta D'Oeste
& NA & 1102 & Leste Rondoniense & 11006 & Cacoal & 110005 & Cacoal & do
Entorno & 1102 & Ji-Paraná & do Entorno & NA & NA & NA & NA & NA &
Centro Local & Centro Local & 1101 & Região Rural da Capital Regional de
Porto Velho & Região Rural de Capital Regional & Sim & Não & Não &
110850.84 & 20336.994 & 73025.07 & 120335.59 & 324548.50 & 16776.193 &
341324.69 & 13266.66 & Administração, defesa, educação e saúde públicas
e seguridade social & Pecuária, inclusive apoio à pecuária & Demais
serviços \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100023 & Ariquemes & NA & 1102
& Leste Rondoniense & 11003 & Ariquemes & 110002 & Ariquemes & Polo &
1101 & Porto Velho & do Entorno & NA & NA & NA & NA & NA & Centro
Sub-regional B & Centro Sub-regional & 1101 & Região Rural da Capital
Regional de Porto Velho & Região Rural de Capital Regional & Sim & Não &
Não & 93249.75 & 354733.212 & 694832.17 & 466732.80 & 1609547.93 &
190304.571 & 1799852.51 & 17772.99 & Administração, defesa, educação e
saúde públicas e seguridade social & Demais serviços & Comércio e
reparação de veículos automotores e motocicletas \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100031 & Cabixi & NA & 1102 &
Leste Rondoniense & 11008 & Colorado do Oeste & 110006 & Vilhena & do
Entorno & 1102 & Ji-Paraná & do Entorno & NA & NA & NA & NA & NA &
Centro Local & Centro Local & 1101 & Região Rural da Capital Regional de
Porto Velho & Região Rural de Capital Regional & Sim & Não & Não &
38259.43 & 3412.205 & 17787.45 & 32838.64 & 92297.72 & 4066.819 &
96364.54 & 14836.73 & Administração, defesa, educação e saúde públicas e
seguridade social & Pecuária, inclusive apoio à pecuária & Agricultura,
inclusive apoio à agricultura e a pós colheita \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100049 & Cacoal & NA & 1102 &
Leste Rondoniense & 11006 & Cacoal & 110005 & Cacoal & Polo & 1102 &
Ji-Paraná & do Entorno & NA & NA & NA & NA & NA & Centro Sub-regional B
& Centro Sub-regional & 5105 & Região Rural do Centro Sub-regional de
Vilhena (RO) e Cacoal (RO) & Região Rural de Centro Sub-regional & Sim &
Não & Não & 140658.88 & 140288.317 & 599519.83 & 395842.23 & 1276309.26
& 156944.241 & 1433253.51 & 16692.33 & Administração, defesa, educação e
saúde públicas e seguridade social & Demais serviços & Comércio e
reparação de veículos automotores e motocicletas \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100056 & Cerejeiras & NA & 1102
& Leste Rondoniense & 11008 & Colorado do Oeste & 110006 & Vilhena & do
Entorno & 1102 & Ji-Paraná & do Entorno & NA & NA & NA & NA & NA &
Centro de Zona B & Centro de Zona & 1101 & Região Rural da Capital
Regional de Porto Velho & Região Rural de Capital Regional & Sim & Não &
Não & 45153.64 & 19889.818 & 149569.44 & 83089.55 & 297702.45 &
55567.232 & 353269.68 & 19581.49 & Administração, defesa, educação e
saúde públicas e seguridade social & Comércio e reparação de veículos
automotores e motocicletas & Demais serviços \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100064 & Colorado do Oeste & NA
& 1102 & Leste Rondoniense & 11008 & Colorado do Oeste & 110006 &
Vilhena & do Entorno & 1102 & Ji-Paraná & do Entorno & NA & NA & NA & NA
& NA & Centro Local & Centro Local & 1101 & Região Rural da Capital
Regional de Porto Velho & Região Rural de Capital Regional & Sim & Não &
Não & 51029.59 & 23179.131 & 66099.41 & 86090.50 & 226398.63 & 16368.611
& 242767.24 & 12650.72 & Administração, defesa, educação e saúde
públicas e seguridade social & Demais serviços & Pecuária, inclusive
apoio à pecuária \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100072 & Corumbiara & NA & 1102
& Leste Rondoniense & 11008 & Colorado do Oeste & 110006 & Vilhena & do
Entorno & 1102 & Ji-Paraná & do Entorno & NA & NA & NA & NA & NA &
Centro Local & Centro Local & 1101 & Região Rural da Capital Regional de
Porto Velho & Região Rural de Capital Regional & Sim & Não & Não &
84717.78 & 8467.812 & 23920.59 & 44882.92 & 161989.10 & 6691.490 &
168680.59 & 18667.62 & Pecuária, inclusive apoio à pecuária &
Administração, defesa, educação e saúde públicas e seguridade social &
Agricultura, inclusive apoio à agricultura e a pós colheita \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100080 & Costa Marques & NA &
1101 & Madeira-Guaporé & 11002 & Guajará-Mirim & 110004 & Ji-Paraná & do
Entorno & 1102 & Ji-Paraná & do Entorno & NA & NA & NA & NA & NA &
Centro Local & Centro Local & 1101 & Região Rural da Capital Regional de
Porto Velho & Região Rural de Capital Regional & Sim & Não & Não &
38194.67 & 6601.178 & 28150.39 & 71667.46 & 144613.70 & 5125.136 &
149738.83 & 9445.46 & Administração, defesa, educação e saúde públicas e
seguridade social & Pecuária, inclusive apoio à pecuária & Demais
serviços \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100098 & Espigão D'Oeste & NA &
1102 & Leste Rondoniense & 11006 & Cacoal & 110005 & Cacoal & do Entorno
& 1102 & Ji-Paraná & do Entorno & NA & NA & NA & NA & NA & Centro Local
& Centro Local & 5105 & Região Rural do Centro Sub-regional de Vilhena
(RO) e Cacoal (RO) & Região Rural de Centro Sub-regional & Sim & Não &
Não & 86783.68 & 50323.880 & 114730.94 & 140055.63 & 391894.13 &
34652.095 & 426546.22 & 13456.14 & Administração, defesa, educação e
saúde públicas e seguridade social & Pecuária, inclusive apoio à
pecuária & Demais serviços \\
2013 & 1 & Norte & 11 & RO & Rondônia & 1100106 & Guajará-Mirim & NA &
1101 & Madeira-Guaporé & 11002 & Guajará-Mirim & 110001 & Porto Velho &
do Entorno & 1101 & Porto Velho & do Entorno & NA & NA & NA & 1100106 &
Internacional de Guajará-Mirim/Brasil - Guayaramerín/Bolívia & Centro de
Zona B & Centro de Zona & 1101 & Região Rural da Capital Regional de
Porto Velho & Região Rural de Capital Regional & Sim & Não & Não &
28195.87 & 26046.566 & 256981.36 & 208747.26 & 519971.05 & 85159.777 &
605130.83 & 13223.72 & Administração, defesa, educação e saúde públicas
e seguridade social & Demais serviços & Comércio e reparação de veículos
automotores e motocicletas \\
\end{longtable}

\textbf{GRÁFICO PIB POR REGIÃO}

\pandocbounded{\includegraphics[keepaspectratio]{Teste-lição_files/figure-latex/unnamed-chunk-15-1.pdf}}

R: Feito!!

\end{document}
